// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FireflyCommunication.proto

package com.SA4E.UEB1.T2.proto;

public final class FireflyCommunication {
  private FireflyCommunication() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UpdateStateRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:UpdateStateRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 posX = 1;</code>
     * @return The posX.
     */
    int getPosX();

    /**
     * <code>int32 posY = 2;</code>
     * @return The posY.
     */
    int getPosY();

    /**
     * <code>double phase = 3;</code>
     * @return The phase.
     */
    double getPhase();
  }
  /**
   * Protobuf type {@code UpdateStateRequest}
   */
  public  static final class UpdateStateRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:UpdateStateRequest)
      UpdateStateRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UpdateStateRequest.newBuilder() to construct.
    private UpdateStateRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UpdateStateRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new UpdateStateRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UpdateStateRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              posX_ = input.readInt32();
              break;
            }
            case 16: {

              posY_ = input.readInt32();
              break;
            }
            case 25: {

              phase_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.SA4E.UEB1.T2.proto.FireflyCommunication.internal_static_UpdateStateRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.SA4E.UEB1.T2.proto.FireflyCommunication.internal_static_UpdateStateRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.SA4E.UEB1.T2.proto.FireflyCommunication.UpdateStateRequest.class, com.SA4E.UEB1.T2.proto.FireflyCommunication.UpdateStateRequest.Builder.class);
    }

    public static final int POSX_FIELD_NUMBER = 1;
    private int posX_;
    /**
     * <code>int32 posX = 1;</code>
     * @return The posX.
     */
    public int getPosX() {
      return posX_;
    }

    public static final int POSY_FIELD_NUMBER = 2;
    private int posY_;
    /**
     * <code>int32 posY = 2;</code>
     * @return The posY.
     */
    public int getPosY() {
      return posY_;
    }

    public static final int PHASE_FIELD_NUMBER = 3;
    private double phase_;
    /**
     * <code>double phase = 3;</code>
     * @return The phase.
     */
    public double getPhase() {
      return phase_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (posX_ != 0) {
        output.writeInt32(1, posX_);
      }
      if (posY_ != 0) {
        output.writeInt32(2, posY_);
      }
      if (phase_ != 0D) {
        output.writeDouble(3, phase_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (posX_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, posX_);
      }
      if (posY_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, posY_);
      }
      if (phase_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, phase_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.SA4E.UEB1.T2.proto.FireflyCommunication.UpdateStateRequest)) {
        return super.equals(obj);
      }
      com.SA4E.UEB1.T2.proto.FireflyCommunication.UpdateStateRequest other = (com.SA4E.UEB1.T2.proto.FireflyCommunication.UpdateStateRequest) obj;

      if (getPosX()
          != other.getPosX()) return false;
      if (getPosY()
          != other.getPosY()) return false;
      if (java.lang.Double.doubleToLongBits(getPhase())
          != java.lang.Double.doubleToLongBits(
              other.getPhase())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + POSX_FIELD_NUMBER;
      hash = (53 * hash) + getPosX();
      hash = (37 * hash) + POSY_FIELD_NUMBER;
      hash = (53 * hash) + getPosY();
      hash = (37 * hash) + PHASE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getPhase()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.SA4E.UEB1.T2.proto.FireflyCommunication.UpdateStateRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.SA4E.UEB1.T2.proto.FireflyCommunication.UpdateStateRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.SA4E.UEB1.T2.proto.FireflyCommunication.UpdateStateRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.SA4E.UEB1.T2.proto.FireflyCommunication.UpdateStateRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.SA4E.UEB1.T2.proto.FireflyCommunication.UpdateStateRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.SA4E.UEB1.T2.proto.FireflyCommunication.UpdateStateRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.SA4E.UEB1.T2.proto.FireflyCommunication.UpdateStateRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.SA4E.UEB1.T2.proto.FireflyCommunication.UpdateStateRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.SA4E.UEB1.T2.proto.FireflyCommunication.UpdateStateRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.SA4E.UEB1.T2.proto.FireflyCommunication.UpdateStateRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.SA4E.UEB1.T2.proto.FireflyCommunication.UpdateStateRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.SA4E.UEB1.T2.proto.FireflyCommunication.UpdateStateRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.SA4E.UEB1.T2.proto.FireflyCommunication.UpdateStateRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code UpdateStateRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:UpdateStateRequest)
        com.SA4E.UEB1.T2.proto.FireflyCommunication.UpdateStateRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.SA4E.UEB1.T2.proto.FireflyCommunication.internal_static_UpdateStateRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.SA4E.UEB1.T2.proto.FireflyCommunication.internal_static_UpdateStateRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.SA4E.UEB1.T2.proto.FireflyCommunication.UpdateStateRequest.class, com.SA4E.UEB1.T2.proto.FireflyCommunication.UpdateStateRequest.Builder.class);
      }

      // Construct using com.SA4E.UEB1.T2.proto.FireflyCommunication.UpdateStateRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        posX_ = 0;

        posY_ = 0;

        phase_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.SA4E.UEB1.T2.proto.FireflyCommunication.internal_static_UpdateStateRequest_descriptor;
      }

      @java.lang.Override
      public com.SA4E.UEB1.T2.proto.FireflyCommunication.UpdateStateRequest getDefaultInstanceForType() {
        return com.SA4E.UEB1.T2.proto.FireflyCommunication.UpdateStateRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.SA4E.UEB1.T2.proto.FireflyCommunication.UpdateStateRequest build() {
        com.SA4E.UEB1.T2.proto.FireflyCommunication.UpdateStateRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.SA4E.UEB1.T2.proto.FireflyCommunication.UpdateStateRequest buildPartial() {
        com.SA4E.UEB1.T2.proto.FireflyCommunication.UpdateStateRequest result = new com.SA4E.UEB1.T2.proto.FireflyCommunication.UpdateStateRequest(this);
        result.posX_ = posX_;
        result.posY_ = posY_;
        result.phase_ = phase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.SA4E.UEB1.T2.proto.FireflyCommunication.UpdateStateRequest) {
          return mergeFrom((com.SA4E.UEB1.T2.proto.FireflyCommunication.UpdateStateRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.SA4E.UEB1.T2.proto.FireflyCommunication.UpdateStateRequest other) {
        if (other == com.SA4E.UEB1.T2.proto.FireflyCommunication.UpdateStateRequest.getDefaultInstance()) return this;
        if (other.getPosX() != 0) {
          setPosX(other.getPosX());
        }
        if (other.getPosY() != 0) {
          setPosY(other.getPosY());
        }
        if (other.getPhase() != 0D) {
          setPhase(other.getPhase());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.SA4E.UEB1.T2.proto.FireflyCommunication.UpdateStateRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.SA4E.UEB1.T2.proto.FireflyCommunication.UpdateStateRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int posX_ ;
      /**
       * <code>int32 posX = 1;</code>
       * @return The posX.
       */
      public int getPosX() {
        return posX_;
      }
      /**
       * <code>int32 posX = 1;</code>
       * @param value The posX to set.
       * @return This builder for chaining.
       */
      public Builder setPosX(int value) {
        
        posX_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 posX = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPosX() {
        
        posX_ = 0;
        onChanged();
        return this;
      }

      private int posY_ ;
      /**
       * <code>int32 posY = 2;</code>
       * @return The posY.
       */
      public int getPosY() {
        return posY_;
      }
      /**
       * <code>int32 posY = 2;</code>
       * @param value The posY to set.
       * @return This builder for chaining.
       */
      public Builder setPosY(int value) {
        
        posY_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 posY = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPosY() {
        
        posY_ = 0;
        onChanged();
        return this;
      }

      private double phase_ ;
      /**
       * <code>double phase = 3;</code>
       * @return The phase.
       */
      public double getPhase() {
        return phase_;
      }
      /**
       * <code>double phase = 3;</code>
       * @param value The phase to set.
       * @return This builder for chaining.
       */
      public Builder setPhase(double value) {
        
        phase_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double phase = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPhase() {
        
        phase_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:UpdateStateRequest)
    }

    // @@protoc_insertion_point(class_scope:UpdateStateRequest)
    private static final com.SA4E.UEB1.T2.proto.FireflyCommunication.UpdateStateRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.SA4E.UEB1.T2.proto.FireflyCommunication.UpdateStateRequest();
    }

    public static com.SA4E.UEB1.T2.proto.FireflyCommunication.UpdateStateRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UpdateStateRequest>
        PARSER = new com.google.protobuf.AbstractParser<UpdateStateRequest>() {
      @java.lang.Override
      public UpdateStateRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UpdateStateRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UpdateStateRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UpdateStateRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.SA4E.UEB1.T2.proto.FireflyCommunication.UpdateStateRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetStateReplyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GetStateReply)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated double values = 1;</code>
     * @return A list containing the values.
     */
    java.util.List<java.lang.Double> getValuesList();
    /**
     * <code>repeated double values = 1;</code>
     * @return The count of values.
     */
    int getValuesCount();
    /**
     * <code>repeated double values = 1;</code>
     * @param index The index of the element to return.
     * @return The values at the given index.
     */
    double getValues(int index);
  }
  /**
   * Protobuf type {@code GetStateReply}
   */
  public  static final class GetStateReply extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GetStateReply)
      GetStateReplyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetStateReply.newBuilder() to construct.
    private GetStateReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetStateReply() {
      values_ = emptyDoubleList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GetStateReply();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GetStateReply(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                values_ = newDoubleList();
                mutable_bitField0_ |= 0x00000001;
              }
              values_.addDouble(input.readDouble());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
                values_ = newDoubleList();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                values_.addDouble(input.readDouble());
              }
              input.popLimit(limit);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          values_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.SA4E.UEB1.T2.proto.FireflyCommunication.internal_static_GetStateReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.SA4E.UEB1.T2.proto.FireflyCommunication.internal_static_GetStateReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.SA4E.UEB1.T2.proto.FireflyCommunication.GetStateReply.class, com.SA4E.UEB1.T2.proto.FireflyCommunication.GetStateReply.Builder.class);
    }

    public static final int VALUES_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.DoubleList values_;
    /**
     * <code>repeated double values = 1;</code>
     * @return A list containing the values.
     */
    public java.util.List<java.lang.Double>
        getValuesList() {
      return values_;
    }
    /**
     * <code>repeated double values = 1;</code>
     * @return The count of values.
     */
    public int getValuesCount() {
      return values_.size();
    }
    /**
     * <code>repeated double values = 1;</code>
     * @param index The index of the element to return.
     * @return The values at the given index.
     */
    public double getValues(int index) {
      return values_.getDouble(index);
    }
    private int valuesMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getValuesList().size() > 0) {
        output.writeUInt32NoTag(10);
        output.writeUInt32NoTag(valuesMemoizedSerializedSize);
      }
      for (int i = 0; i < values_.size(); i++) {
        output.writeDoubleNoTag(values_.getDouble(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        dataSize = 8 * getValuesList().size();
        size += dataSize;
        if (!getValuesList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        valuesMemoizedSerializedSize = dataSize;
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.SA4E.UEB1.T2.proto.FireflyCommunication.GetStateReply)) {
        return super.equals(obj);
      }
      com.SA4E.UEB1.T2.proto.FireflyCommunication.GetStateReply other = (com.SA4E.UEB1.T2.proto.FireflyCommunication.GetStateReply) obj;

      if (!getValuesList()
          .equals(other.getValuesList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getValuesCount() > 0) {
        hash = (37 * hash) + VALUES_FIELD_NUMBER;
        hash = (53 * hash) + getValuesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.SA4E.UEB1.T2.proto.FireflyCommunication.GetStateReply parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.SA4E.UEB1.T2.proto.FireflyCommunication.GetStateReply parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.SA4E.UEB1.T2.proto.FireflyCommunication.GetStateReply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.SA4E.UEB1.T2.proto.FireflyCommunication.GetStateReply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.SA4E.UEB1.T2.proto.FireflyCommunication.GetStateReply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.SA4E.UEB1.T2.proto.FireflyCommunication.GetStateReply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.SA4E.UEB1.T2.proto.FireflyCommunication.GetStateReply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.SA4E.UEB1.T2.proto.FireflyCommunication.GetStateReply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.SA4E.UEB1.T2.proto.FireflyCommunication.GetStateReply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.SA4E.UEB1.T2.proto.FireflyCommunication.GetStateReply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.SA4E.UEB1.T2.proto.FireflyCommunication.GetStateReply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.SA4E.UEB1.T2.proto.FireflyCommunication.GetStateReply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.SA4E.UEB1.T2.proto.FireflyCommunication.GetStateReply prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GetStateReply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GetStateReply)
        com.SA4E.UEB1.T2.proto.FireflyCommunication.GetStateReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.SA4E.UEB1.T2.proto.FireflyCommunication.internal_static_GetStateReply_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.SA4E.UEB1.T2.proto.FireflyCommunication.internal_static_GetStateReply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.SA4E.UEB1.T2.proto.FireflyCommunication.GetStateReply.class, com.SA4E.UEB1.T2.proto.FireflyCommunication.GetStateReply.Builder.class);
      }

      // Construct using com.SA4E.UEB1.T2.proto.FireflyCommunication.GetStateReply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        values_ = emptyDoubleList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.SA4E.UEB1.T2.proto.FireflyCommunication.internal_static_GetStateReply_descriptor;
      }

      @java.lang.Override
      public com.SA4E.UEB1.T2.proto.FireflyCommunication.GetStateReply getDefaultInstanceForType() {
        return com.SA4E.UEB1.T2.proto.FireflyCommunication.GetStateReply.getDefaultInstance();
      }

      @java.lang.Override
      public com.SA4E.UEB1.T2.proto.FireflyCommunication.GetStateReply build() {
        com.SA4E.UEB1.T2.proto.FireflyCommunication.GetStateReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.SA4E.UEB1.T2.proto.FireflyCommunication.GetStateReply buildPartial() {
        com.SA4E.UEB1.T2.proto.FireflyCommunication.GetStateReply result = new com.SA4E.UEB1.T2.proto.FireflyCommunication.GetStateReply(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) != 0)) {
          values_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.values_ = values_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.SA4E.UEB1.T2.proto.FireflyCommunication.GetStateReply) {
          return mergeFrom((com.SA4E.UEB1.T2.proto.FireflyCommunication.GetStateReply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.SA4E.UEB1.T2.proto.FireflyCommunication.GetStateReply other) {
        if (other == com.SA4E.UEB1.T2.proto.FireflyCommunication.GetStateReply.getDefaultInstance()) return this;
        if (!other.values_.isEmpty()) {
          if (values_.isEmpty()) {
            values_ = other.values_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureValuesIsMutable();
            values_.addAll(other.values_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.SA4E.UEB1.T2.proto.FireflyCommunication.GetStateReply parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.SA4E.UEB1.T2.proto.FireflyCommunication.GetStateReply) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.Internal.DoubleList values_ = emptyDoubleList();
      private void ensureValuesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          values_ = mutableCopy(values_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated double values = 1;</code>
       * @return A list containing the values.
       */
      public java.util.List<java.lang.Double>
          getValuesList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(values_) : values_;
      }
      /**
       * <code>repeated double values = 1;</code>
       * @return The count of values.
       */
      public int getValuesCount() {
        return values_.size();
      }
      /**
       * <code>repeated double values = 1;</code>
       * @param index The index of the element to return.
       * @return The values at the given index.
       */
      public double getValues(int index) {
        return values_.getDouble(index);
      }
      /**
       * <code>repeated double values = 1;</code>
       * @param index The index to set the value at.
       * @param value The values to set.
       * @return This builder for chaining.
       */
      public Builder setValues(
          int index, double value) {
        ensureValuesIsMutable();
        values_.setDouble(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double values = 1;</code>
       * @param value The values to add.
       * @return This builder for chaining.
       */
      public Builder addValues(double value) {
        ensureValuesIsMutable();
        values_.addDouble(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double values = 1;</code>
       * @param values The values to add.
       * @return This builder for chaining.
       */
      public Builder addAllValues(
          java.lang.Iterable<? extends java.lang.Double> values) {
        ensureValuesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, values_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double values = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearValues() {
        values_ = emptyDoubleList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GetStateReply)
    }

    // @@protoc_insertion_point(class_scope:GetStateReply)
    private static final com.SA4E.UEB1.T2.proto.FireflyCommunication.GetStateReply DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.SA4E.UEB1.T2.proto.FireflyCommunication.GetStateReply();
    }

    public static com.SA4E.UEB1.T2.proto.FireflyCommunication.GetStateReply getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetStateReply>
        PARSER = new com.google.protobuf.AbstractParser<GetStateReply>() {
      @java.lang.Override
      public GetStateReply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetStateReply(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetStateReply> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetStateReply> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.SA4E.UEB1.T2.proto.FireflyCommunication.GetStateReply getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateStateRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateStateRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetStateReply_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetStateReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032FireflyCommunication.proto\"?\n\022UpdateSt" +
      "ateRequest\022\014\n\004posX\030\001 \001(\005\022\014\n\004posY\030\002 \001(\005\022\r" +
      "\n\005phase\030\003 \001(\001\"\037\n\rGetStateReply\022\016\n\006values" +
      "\030\001 \003(\0012?\n\007Updater\0224\n\013updateState\022\023.Updat" +
      "eStateRequest\032\016.GetStateReply\"\000B\007\n\005proto" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_UpdateStateRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_UpdateStateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateStateRequest_descriptor,
        new java.lang.String[] { "PosX", "PosY", "Phase", });
    internal_static_GetStateReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GetStateReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetStateReply_descriptor,
        new java.lang.String[] { "Values", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
